<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: collector.proto

namespace Hoten\OpenTracingBundle\Proto\GPBMetadata;

class Collector
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abb020a0f636f6c6c6563746f722e70726f746f121d486f74656e2e4f70" .
            "656e54726163696e6742756e646c652e50726f746f2280020a0d436f6c6c" .
            "6563745061636b657412410a047370616e18012001280b32332e486f7465" .
            "6e2e4f70656e54726163696e6742756e646c652e50726f746f2e436f6c6c" .
            "6563745061636b65742e5370616e4944124b0a0a616e6e6f746174696f6e" .
            "18022003280b32372e486f74656e2e4f70656e54726163696e6742756e64" .
            "6c652e50726f746f2e436f6c6c6563745061636b65742e416e6e6f746174" .
            "696f6e1a350a065370616e4944120d0a057472616365180120012806120c" .
            "0a047370616e180220012806120e0a06706172656e741803200128061a28" .
            "0a0a416e6e6f746174696f6e120b0a036b6579180120012809120d0a0576" .
            "616c756518022001280c620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

