services:
  open_tracing.event_bus:
    alias: event_bus

  open_tracing.logger:
    alias: logger

  open_tracing.encoder:
    class: "%open_tracing.encoder%"

  open_tracing.transport.http:
    class: DDTrace\Transport\Http
    arguments:
      - "@open_tracing.encoder"
      - "@open_tracing.logger"
      - endpoint: "%open_tracing.endpoint%"

  open_tracing.transport.tcp:
    class: Hoten\OpenTracingBundle\Transport\TcpTransport
    arguments:
      - "@open_tracing.encoder"
      - "@open_tracing.logger"
      - host: "%open_tracing.host%"
        port: "%open_tracing.port%"

  open_tracing.transport.noop:
    class: DDTrace\Transport\Noop

  open_tracing.tracing_starter:
    class: Hoten\OpenTracingBundle\Listeners\TracingStarter
    arguments:
      - "@event_dispatcher"
      - "@open_tracing.tracer"
      - "%kernel.environment%"
    tags:
      - { name: kernel.event_listener, event: kernel.controller }

  open_tracing.tracing_terminator:
    class: Hoten\OpenTracingBundle\Listeners\TracingTerminator
    arguments:
      - "@open_tracing.tracer"
      - "@open_tracing.event_bus"
    tags:
      - { name: kernel.event_listener, event: kernel.terminate, priority: -1000 }
      - { name: kernel.event_listener, event: kernel.exception, priority: -1000 }

  open_tracing.tracer_factory:
    class: Hoten\OpenTracingBundle\Tracers\TracerFactory

  open_tracing.tracer:
    class: OpenTracing\Tracer
    public: true
    factory: ["@open_tracing.tracer_factory", "build"]
    arguments:
      - "%open_tracing.enabled%"
      - "%open_tracing.sample%"
      - "@open_tracing.transport"

  open_tracing.listener.tracer_flusher:
    class: Hoten\OpenTracingBundle\Listeners\TracingFlusher
    arguments:
      - "@open_tracing.logger"
    tags:
        - { name: event_subscriber, subscribes_to: Hoten\OpenTracingBundle\Events\TracingTerminated }

  open_tracing.http_client_provider:
    class: Hoten\OpenTracingBundle\Service\HttpClientProvider
    arguments:
      - "@open_tracing.tracer"
      - "%open_tracing.format%"
        